/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.assyifacake.views.Produk;

import static com.assyifacake.db.KoneksiDatabase.getConnection;
import com.assyifacake.helpers.validations.exceptions.NonAlphanumericException;
import com.assyifacake.helpers.validations.AlphanumericValidation;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class LihatProduk extends javax.swing.JFrame {

    /**
     * Creates new form LihatProduk
     */
    Connection conn = null;
    PreparedStatement pS = null;
    ResultSet rS = null;  
    
    int offSet = 0;
    
    Map<Integer,JLabel> image = new HashMap<Integer,JLabel>();
    Map<Integer,JLabel> namaImage = new HashMap<Integer, JLabel>();
    
    public LihatProduk() {
            
            initComponents();
            image.put(1, image1);
            image.put(2, image2);
            image.put(3, image3);
            image.put(4, image4);
            image.put(5, image5);
            image.put(6, image6);
            namaImage.put(1, namaImage1);
            namaImage.put(2, namaImage2);
            namaImage.put(3, namaImage3);
            namaImage.put(4, namaImage4);
            namaImage.put(5, namaImage5);
            namaImage.put(6, namaImage6);            
            String sql = "SELECT * FROM fileUpload LIMIT 6";
            tampilGambar(sql);
                    
    }
    
    public void kosonginGambar() {
        
        for(int i=1; i <= image.size(); i++) {
        image.get(i).setIcon(null);
        namaImage.get(i).setText("");
        }
    }
    
    
    public void  tampilGambar(String sql) {
        Runnable runnable = new Runnable() {
            @Override
            public void run() {   
                
                try {
                    kosonginGambar();
                    conn = getConnection();
                    pS = getConnection().prepareStatement(sql);
                    rS = pS.executeQuery();  
                    int i =1;
                    while(rS.next()) {
                        byte[] getBytes = rS.getBytes("gambar");
                        String namaDariDb = rS.getString("nama");
                        ByteArrayInputStream inputStream = new ByteArrayInputStream(getBytes);            
                        BufferedImage gambar = ImageIO.read(inputStream); 
                        ImageIcon iconBelumResized = new ImageIcon(gambar);
                        Image resizedImage = iconBelumResized.getImage().getScaledInstance(150, 150, SCALE_SMOOTH);
                        ImageIcon icon = new ImageIcon(resizedImage);


                        image.get(i).setIcon(icon);
                        namaImage.get(i).setText(namaDariDb);                
                        i++;

                    }

                    if(i<=6) {
                        nextBT.setEnabled(false);
                    } else {
                        nextBT.setEnabled(true);
                    }

                    if(offSet == 0) {
                        prevBT.setEnabled(false);
                    } else{
                        prevBT.setEnabled(true);
                    }


                } catch (SQLException | IOException ex) {
                    Logger.getLogger(LihatProduk.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        conn.close();
                        rS.close();
                        pS.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(LihatProduk.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        var thread = new Thread(runnable);
        thread.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image2 = new javax.swing.JLabel();
        image3 = new javax.swing.JLabel();
        image4 = new javax.swing.JLabel();
        image5 = new javax.swing.JLabel();
        image6 = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        prevBT = new javax.swing.JButton();
        nextBT = new javax.swing.JButton();
        namaImage3 = new javax.swing.JLabel();
        namaImage2 = new javax.swing.JLabel();
        namaImage1 = new javax.swing.JLabel();
        namaImage4 = new javax.swing.JLabel();
        namaImage5 = new javax.swing.JLabel();
        namaImage6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        image6.setForeground(new java.awt.Color(102, 255, 204));

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });

        prevBT.setText("Prev");
        prevBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevBTMouseClicked(evt);
            }
        });
        prevBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBTActionPerformed(evt);
            }
        });

        nextBT.setText("Next");
        nextBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextBTMouseClicked(evt);
            }
        });
        nextBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTActionPerformed(evt);
            }
        });

        namaImage3.setText("jLabel1");

        namaImage2.setText("jLabel1");

        namaImage1.setText("jLabel1");

        namaImage4.setText("jLabel1");

        namaImage5.setText("jLabel1");

        namaImage6.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(namaImage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaImage2)
                .addGap(156, 156, 156)
                .addComponent(namaImage3)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prevBT)
                            .addComponent(image4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(nextBT))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(image5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(image3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(image6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(namaImage4)
                .addGap(160, 160, 160)
                .addComponent(namaImage5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaImage6)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(image3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaImage3)
                    .addComponent(namaImage2)
                    .addComponent(namaImage1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaImage4)
                    .addComponent(namaImage5)
                    .addComponent(namaImage6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevBT)
                    .addComponent(nextBT))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        
        offSet =0;
                
        
        String ketikan = search.getText();
        try {
            AlphanumericValidation.validate(ketikan);
        } catch (NonAlphanumericException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            search.setText("");
            return;
        }
        String sql =  "SELECT * FROM fileUpload WHERE nama like '%"+ketikan+"%' LIMIT 6";    
    
        tampilGambar(sql);
                
     
    }//GEN-LAST:event_searchKeyTyped

    private void nextBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBTMouseClicked
     
    }//GEN-LAST:event_nextBTMouseClicked

    private void prevBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevBTMouseClicked
        
    }//GEN-LAST:event_prevBTMouseClicked

    private void prevBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBTActionPerformed
        if(!nextBT.isEnabled()){
            nextBT.setEnabled(true);
        }
        
        offSet-= 6;        
        if(search.getText().isBlank()) {

            String sql =  "SELECT * FROM fileUpload LIMIT 6 OFFSET " + offSet;    
            tampilGambar(sql);
            
        } else {
            String ketikan = search.getText();
            String sql =  "SELECT * FROM fileUpload WHERE nama LIKE '%"+ketikan+"%' LIMIT 6 OFFSET " +offSet;  
            tampilGambar(sql);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_prevBTActionPerformed

    private void nextBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTActionPerformed
        // TODO add your handling code here:
        if(!prevBT.isEnabled()){
            prevBT.setEnabled(true);
        }    
        offSet+= 6;        
        if(search.getText().isBlank()) {

            String sql =  "SELECT * FROM fileUpload LIMIT 6 OFFSET " + offSet;    
            tampilGambar(sql);
            
        } else {
            String ketikan = search.getText();
            String sql =  "SELECT * FROM fileUpload WHERE nama LIKE '%"+ketikan+"%' LIMIT 6 OFFSET " +offSet;  
            tampilGambar(sql);

        }
                
    }//GEN-LAST:event_nextBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JLabel image4;
    private javax.swing.JLabel image5;
    private javax.swing.JLabel image6;
    private javax.swing.JLabel namaImage1;
    private javax.swing.JLabel namaImage2;
    private javax.swing.JLabel namaImage3;
    private javax.swing.JLabel namaImage4;
    private javax.swing.JLabel namaImage5;
    private javax.swing.JLabel namaImage6;
    private javax.swing.JButton nextBT;
    private javax.swing.JButton prevBT;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
